//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.11 at 06:19:01 PM KST 
//


package com.ups.shipping.shipacceptresponse;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}TrackingNumber"/&gt;
 *         &lt;element ref="{}BaseServiceCharge" minOccurs="0"/&gt;
 *         &lt;element ref="{}ServiceOptionsCharges" minOccurs="0"/&gt;
 *         &lt;element ref="{}LabelImage" minOccurs="0"/&gt;
 *         &lt;element ref="{}Receipt" minOccurs="0"/&gt;
 *         &lt;element name="USPSPICNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CN22Number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Form" type="{}IntlForms" minOccurs="0"/&gt;
 *         &lt;element ref="{}Accessorial" minOccurs="0"/&gt;
 *         &lt;element ref="{}ItemizedCharges" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}NegotiatedCharges" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trackingNumber",
    "baseServiceCharge",
    "serviceOptionsCharges",
    "labelImage",
    "receipt",
    "uspspicNumber",
    "cn22Number",
    "form",
    "accessorial",
    "itemizedCharges",
    "negotiatedCharges"
})
@XmlRootElement(name = "PackageResults")
public class PackageResults {

    @XmlElement(name = "TrackingNumber", required = true)
    protected String trackingNumber;
    @XmlElement(name = "BaseServiceCharge")
    protected MonetaryType baseServiceCharge;
    @XmlElement(name = "ServiceOptionsCharges")
    protected MonetaryType serviceOptionsCharges;
    @XmlElement(name = "LabelImage")
    protected LabelImage labelImage;
    @XmlElement(name = "Receipt")
    protected Receipt receipt;
    @XmlElement(name = "USPSPICNumber")
    protected String uspspicNumber;
    @XmlElement(name = "CN22Number")
    protected String cn22Number;
    @XmlElement(name = "Form")
    protected IntlForms form;
    @XmlElement(name = "Accessorial")
    protected Accessorial accessorial;
    @XmlElement(name = "ItemizedCharges")
    protected List<MonetaryType> itemizedCharges;
    @XmlElement(name = "NegotiatedCharges")
    protected NegotiatedCharges negotiatedCharges;

    /**
     * Gets the value of the trackingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackingNumber() {
        return trackingNumber;
    }

    /**
     * Sets the value of the trackingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackingNumber(String value) {
        this.trackingNumber = value;
    }

    /**
     * Gets the value of the baseServiceCharge property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryType }
     *     
     */
    public MonetaryType getBaseServiceCharge() {
        return baseServiceCharge;
    }

    /**
     * Sets the value of the baseServiceCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryType }
     *     
     */
    public void setBaseServiceCharge(MonetaryType value) {
        this.baseServiceCharge = value;
    }

    /**
     * Gets the value of the serviceOptionsCharges property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryType }
     *     
     */
    public MonetaryType getServiceOptionsCharges() {
        return serviceOptionsCharges;
    }

    /**
     * Sets the value of the serviceOptionsCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryType }
     *     
     */
    public void setServiceOptionsCharges(MonetaryType value) {
        this.serviceOptionsCharges = value;
    }

    /**
     * Gets the value of the labelImage property.
     * 
     * @return
     *     possible object is
     *     {@link LabelImage }
     *     
     */
    public LabelImage getLabelImage() {
        return labelImage;
    }

    /**
     * Sets the value of the labelImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelImage }
     *     
     */
    public void setLabelImage(LabelImage value) {
        this.labelImage = value;
    }

    /**
     * Gets the value of the receipt property.
     * 
     * @return
     *     possible object is
     *     {@link Receipt }
     *     
     */
    public Receipt getReceipt() {
        return receipt;
    }

    /**
     * Sets the value of the receipt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Receipt }
     *     
     */
    public void setReceipt(Receipt value) {
        this.receipt = value;
    }

    /**
     * Gets the value of the uspspicNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSPSPICNumber() {
        return uspspicNumber;
    }

    /**
     * Sets the value of the uspspicNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSPSPICNumber(String value) {
        this.uspspicNumber = value;
    }

    /**
     * Gets the value of the cn22Number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCN22Number() {
        return cn22Number;
    }

    /**
     * Sets the value of the cn22Number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCN22Number(String value) {
        this.cn22Number = value;
    }

    /**
     * Gets the value of the form property.
     * 
     * @return
     *     possible object is
     *     {@link IntlForms }
     *     
     */
    public IntlForms getForm() {
        return form;
    }

    /**
     * Sets the value of the form property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntlForms }
     *     
     */
    public void setForm(IntlForms value) {
        this.form = value;
    }

    /**
     * Gets the value of the accessorial property.
     * 
     * @return
     *     possible object is
     *     {@link Accessorial }
     *     
     */
    public Accessorial getAccessorial() {
        return accessorial;
    }

    /**
     * Sets the value of the accessorial property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accessorial }
     *     
     */
    public void setAccessorial(Accessorial value) {
        this.accessorial = value;
    }

    /**
     * Gets the value of the itemizedCharges property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemizedCharges property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemizedCharges().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MonetaryType }
     * 
     * 
     */
    public List<MonetaryType> getItemizedCharges() {
        if (itemizedCharges == null) {
            itemizedCharges = new ArrayList<MonetaryType>();
        }
        return this.itemizedCharges;
    }

    /**
     * Gets the value of the negotiatedCharges property.
     * 
     * @return
     *     possible object is
     *     {@link NegotiatedCharges }
     *     
     */
    public NegotiatedCharges getNegotiatedCharges() {
        return negotiatedCharges;
    }

    /**
     * Sets the value of the negotiatedCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link NegotiatedCharges }
     *     
     */
    public void setNegotiatedCharges(NegotiatedCharges value) {
        this.negotiatedCharges = value;
    }

}
