//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.11 at 06:23:42 PM KST 
//


package com.ups.shipping.shipconfirmresponse;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;
import lombok.ToString;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Response"/&gt;
 *         &lt;element ref="{}ShipmentCharges" minOccurs="0"/&gt;
 *         &lt;element ref="{}BillingWeight"/&gt;
 *         &lt;element ref="{}ShipmentIdentificationNumber"/&gt;
 *         &lt;element ref="{}MIDualReturnShipmentKey" minOccurs="0"/&gt;
 *         &lt;element ref="{}BillableWeightCalculationMethod" minOccurs="0"/&gt;
 *         &lt;element ref="{}RatingMethod" minOccurs="0"/&gt;
 *         &lt;element name="Disclaimer" type="{}DisclaimerType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}ShipmentDigest"/&gt;
 *         &lt;element ref="{}NegotiatedRates" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "response",
    "shipmentCharges",
    "billingWeight",
    "shipmentIdentificationNumber",
    "miDualReturnShipmentKey",
    "billableWeightCalculationMethod",
    "ratingMethod",
    "disclaimer",
    "shipmentDigest",
    "negotiatedRates"
})
@XmlRootElement(name = "ShipmentConfirmResponse")
@ToString
public class ShipmentConfirmResponse {

    @XmlElement(name = "Response", required = true)
    protected Response response;
    @XmlElement(name = "ShipmentCharges")
    protected ShipmentCharges shipmentCharges;
    @XmlElement(name = "BillingWeight", required = true)
    protected BillingWeight billingWeight;
    @XmlElement(name = "ShipmentIdentificationNumber", required = true)
    protected String shipmentIdentificationNumber;
    @XmlElement(name = "MIDualReturnShipmentKey")
    protected String miDualReturnShipmentKey;
    @XmlElement(name = "BillableWeightCalculationMethod")
    protected String billableWeightCalculationMethod;
    @XmlElement(name = "RatingMethod")
    protected String ratingMethod;
    @XmlElement(name = "Disclaimer")
    protected List<DisclaimerType> disclaimer;
    @XmlElement(name = "ShipmentDigest", required = true)
    protected String shipmentDigest;
    @XmlElement(name = "NegotiatedRates")
    protected NegotiatedRates negotiatedRates;

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link Response }
     *     
     */
    public Response getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response }
     *     
     */
    public void setResponse(Response value) {
        this.response = value;
    }

    /**
     * Gets the value of the shipmentCharges property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentCharges }
     *     
     */
    public ShipmentCharges getShipmentCharges() {
        return shipmentCharges;
    }

    /**
     * Sets the value of the shipmentCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentCharges }
     *     
     */
    public void setShipmentCharges(ShipmentCharges value) {
        this.shipmentCharges = value;
    }

    /**
     * Gets the value of the billingWeight property.
     * 
     * @return
     *     possible object is
     *     {@link BillingWeight }
     *     
     */
    public BillingWeight getBillingWeight() {
        return billingWeight;
    }

    /**
     * Sets the value of the billingWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillingWeight }
     *     
     */
    public void setBillingWeight(BillingWeight value) {
        this.billingWeight = value;
    }

    /**
     * Gets the value of the shipmentIdentificationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipmentIdentificationNumber() {
        return shipmentIdentificationNumber;
    }

    /**
     * Sets the value of the shipmentIdentificationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipmentIdentificationNumber(String value) {
        this.shipmentIdentificationNumber = value;
    }

    /**
     * Gets the value of the miDualReturnShipmentKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMIDualReturnShipmentKey() {
        return miDualReturnShipmentKey;
    }

    /**
     * Sets the value of the miDualReturnShipmentKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMIDualReturnShipmentKey(String value) {
        this.miDualReturnShipmentKey = value;
    }

    /**
     * Gets the value of the billableWeightCalculationMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillableWeightCalculationMethod() {
        return billableWeightCalculationMethod;
    }

    /**
     * Sets the value of the billableWeightCalculationMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillableWeightCalculationMethod(String value) {
        this.billableWeightCalculationMethod = value;
    }

    /**
     * Gets the value of the ratingMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRatingMethod() {
        return ratingMethod;
    }

    /**
     * Sets the value of the ratingMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRatingMethod(String value) {
        this.ratingMethod = value;
    }

    /**
     * Gets the value of the disclaimer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the disclaimer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisclaimer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DisclaimerType }
     * 
     * 
     */
    public List<DisclaimerType> getDisclaimer() {
        if (disclaimer == null) {
            disclaimer = new ArrayList<DisclaimerType>();
        }
        return this.disclaimer;
    }

    /**
     * Gets the value of the shipmentDigest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipmentDigest() {
        return shipmentDigest;
    }

    /**
     * Sets the value of the shipmentDigest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipmentDigest(String value) {
        this.shipmentDigest = value;
    }

    /**
     * Gets the value of the negotiatedRates property.
     * 
     * @return
     *     possible object is
     *     {@link NegotiatedRates }
     *     
     */
    public NegotiatedRates getNegotiatedRates() {
        return negotiatedRates;
    }

    /**
     * Sets the value of the negotiatedRates property.
     * 
     * @param value
     *     allowed object is
     *     {@link NegotiatedRates }
     *     
     */
    public void setNegotiatedRates(NegotiatedRates value) {
        this.negotiatedRates = value;
    }

}
