//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.11 at 11:30:01 AM KST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ups.com/XMLSchema/UXOLT/Common/v1.0")
package com.ups.tracking.trackrequest;
