//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.11 at 11:30:01 AM KST 
//


package com.ups.tracking.trackrequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ResponseStatus" type="{http://www.ups.com/XMLSchema/UXOLT/Common/v1.0}CodeDescriptionType"/&gt;
 *         &lt;element name="Alert" type="{http://www.ups.com/XMLSchema/UXOLT/Common/v1.0}CodeDescriptionType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="AlertDetail" type="{http://www.ups.com/XMLSchema/UXOLT/Common/v1.0}DetailType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="TransactionReference" type="{http://www.ups.com/XMLSchema/UXOLT/Common/v1.0}TransactionReferenceType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseType", propOrder = {
    "responseStatus",
    "alert",
    "alertDetail",
    "transactionReference"
})
public class ResponseType {

    @XmlElement(name = "ResponseStatus", namespace = "http://www.ups.com/XMLSchema/UXOLT/Common/v1.0", required = true)
    protected CodeDescriptionType responseStatus;
    @XmlElement(name = "Alert", namespace = "http://www.ups.com/XMLSchema/UXOLT/Common/v1.0")
    protected List<CodeDescriptionType> alert;
    @XmlElement(name = "AlertDetail", namespace = "http://www.ups.com/XMLSchema/UXOLT/Common/v1.0")
    protected List<DetailType> alertDetail;
    @XmlElement(name = "TransactionReference", namespace = "http://www.ups.com/XMLSchema/UXOLT/Common/v1.0")
    protected TransactionReferenceType transactionReference;

    /**
     * Gets the value of the responseStatus property.
     * 
     * @return
     *     possible object is
     *     {@link CodeDescriptionType }
     *     
     */
    public CodeDescriptionType getResponseStatus() {
        return responseStatus;
    }

    /**
     * Sets the value of the responseStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeDescriptionType }
     *     
     */
    public void setResponseStatus(CodeDescriptionType value) {
        this.responseStatus = value;
    }

    /**
     * Gets the value of the alert property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alert property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlert().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeDescriptionType }
     * 
     * 
     */
    public List<CodeDescriptionType> getAlert() {
        if (alert == null) {
            alert = new ArrayList<CodeDescriptionType>();
        }
        return this.alert;
    }

    /**
     * Gets the value of the alertDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alertDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlertDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DetailType }
     * 
     * 
     */
    public List<DetailType> getAlertDetail() {
        if (alertDetail == null) {
            alertDetail = new ArrayList<DetailType>();
        }
        return this.alertDetail;
    }

    /**
     * Gets the value of the transactionReference property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionReferenceType }
     *     
     */
    public TransactionReferenceType getTransactionReference() {
        return transactionReference;
    }

    /**
     * Sets the value of the transactionReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionReferenceType }
     *     
     */
    public void setTransactionReference(TransactionReferenceType value) {
        this.transactionReference = value;
    }

}
