//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.11 at 06:23:24 PM KST 
//


package com.ups.shipping.shipconfirmrequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContactsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContactsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ForwardAgent" type="{}ForwardAgentType" minOccurs="0"/&gt;
 *         &lt;element name="UltimateConsignee" type="{}UltimateConsigneeType" minOccurs="0"/&gt;
 *         &lt;element name="IntermediateConsignee" type="{}IntermediateConsigneeType" minOccurs="0"/&gt;
 *         &lt;element name="Producer" type="{}ProducerType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContactsType", propOrder = {
    "forwardAgent",
    "ultimateConsignee",
    "intermediateConsignee",
    "producer"
})
public class ContactsType {

    @XmlElement(name = "ForwardAgent")
    protected ForwardAgentType forwardAgent;
    @XmlElement(name = "UltimateConsignee")
    protected UltimateConsigneeType ultimateConsignee;
    @XmlElement(name = "IntermediateConsignee")
    protected IntermediateConsigneeType intermediateConsignee;
    @XmlElement(name = "Producer")
    protected ProducerType producer;

    /**
     * Gets the value of the forwardAgent property.
     * 
     * @return
     *     possible object is
     *     {@link ForwardAgentType }
     *     
     */
    public ForwardAgentType getForwardAgent() {
        return forwardAgent;
    }

    /**
     * Sets the value of the forwardAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForwardAgentType }
     *     
     */
    public void setForwardAgent(ForwardAgentType value) {
        this.forwardAgent = value;
    }

    /**
     * Gets the value of the ultimateConsignee property.
     * 
     * @return
     *     possible object is
     *     {@link UltimateConsigneeType }
     *     
     */
    public UltimateConsigneeType getUltimateConsignee() {
        return ultimateConsignee;
    }

    /**
     * Sets the value of the ultimateConsignee property.
     * 
     * @param value
     *     allowed object is
     *     {@link UltimateConsigneeType }
     *     
     */
    public void setUltimateConsignee(UltimateConsigneeType value) {
        this.ultimateConsignee = value;
    }

    /**
     * Gets the value of the intermediateConsignee property.
     * 
     * @return
     *     possible object is
     *     {@link IntermediateConsigneeType }
     *     
     */
    public IntermediateConsigneeType getIntermediateConsignee() {
        return intermediateConsignee;
    }

    /**
     * Sets the value of the intermediateConsignee property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntermediateConsigneeType }
     *     
     */
    public void setIntermediateConsignee(IntermediateConsigneeType value) {
        this.intermediateConsignee = value;
    }

    /**
     * Gets the value of the producer property.
     * 
     * @return
     *     possible object is
     *     {@link ProducerType }
     *     
     */
    public ProducerType getProducer() {
        return producer;
    }

    /**
     * Sets the value of the producer property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProducerType }
     *     
     */
    public void setProducer(ProducerType value) {
        this.producer = value;
    }

}
