//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.11 at 06:23:24 PM KST 
//


package com.ups.shipping.shipconfirmrequest;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentInformationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="Prepaid" type="{}PrepaidType" minOccurs="0"/&gt;
 *         &lt;element name="BillThirdParty" type="{}BillThirdPartyType" minOccurs="0"/&gt;
 *         &lt;element name="FreightCollect" type="{}FreightCollectType" minOccurs="0"/&gt;
 *         &lt;element name="ConsigneeBilled" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@NoArgsConstructor
@AllArgsConstructor
@Builder
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentInformationType", propOrder = {
    "prepaid",
    "billThirdParty",
    "freightCollect",
    "consigneeBilled"
})
public class PaymentInformationType {

    @XmlElement(name = "Prepaid")
    protected PrepaidType prepaid;
    @XmlElement(name = "BillThirdParty")
    protected BillThirdPartyType billThirdParty;
    @XmlElement(name = "FreightCollect")
    protected FreightCollectType freightCollect;
    @XmlElement(name = "ConsigneeBilled")
    protected String consigneeBilled;

    /**
     * Gets the value of the prepaid property.
     * 
     * @return
     *     possible object is
     *     {@link PrepaidType }
     *     
     */
    public PrepaidType getPrepaid() {
        return prepaid;
    }

    /**
     * Sets the value of the prepaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrepaidType }
     *     
     */
    public void setPrepaid(PrepaidType value) {
        this.prepaid = value;
    }

    /**
     * Gets the value of the billThirdParty property.
     * 
     * @return
     *     possible object is
     *     {@link BillThirdPartyType }
     *     
     */
    public BillThirdPartyType getBillThirdParty() {
        return billThirdParty;
    }

    /**
     * Sets the value of the billThirdParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillThirdPartyType }
     *     
     */
    public void setBillThirdParty(BillThirdPartyType value) {
        this.billThirdParty = value;
    }

    /**
     * Gets the value of the freightCollect property.
     * 
     * @return
     *     possible object is
     *     {@link FreightCollectType }
     *     
     */
    public FreightCollectType getFreightCollect() {
        return freightCollect;
    }

    /**
     * Sets the value of the freightCollect property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreightCollectType }
     *     
     */
    public void setFreightCollect(FreightCollectType value) {
        this.freightCollect = value;
    }

    /**
     * Gets the value of the consigneeBilled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsigneeBilled() {
        return consigneeBilled;
    }

    /**
     * Sets the value of the consigneeBilled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsigneeBilled(String value) {
        this.consigneeBilled = value;
    }

}
