//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.11 at 06:23:24 PM KST 
//


package com.ups.shipping.shipconfirmrequest;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ShipmentServiceOptionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShipmentServiceOptionsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SaturdayDelivery" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SaturdayPickupIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="COD" type="{}ShipmentServiceOptionsCODType" minOccurs="0"/&gt;
 *         &lt;element name="AccessPointCOD" type="{}ShipmentServiceOptionsAccessPointCODType" minOccurs="0"/&gt;
 *         &lt;element name="DeliverToAddresseeOnlyIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DirectDeliveryOnlyIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Notification" type="{}ShipmentServiceOptionsNotificationType" maxOccurs="3" minOccurs="0"/&gt;
 *         &lt;element name="LabelDelivery" type="{}LabelDeliveryType" minOccurs="0"/&gt;
 *         &lt;element name="InternationalForms" type="{}InternationalFormsType" minOccurs="0"/&gt;
 *         &lt;element name="ReturnOfDocumentIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DeliveryConfirmation" type="{}ShipmentServiceOptionsDeliveryConfirmationType" minOccurs="0"/&gt;
 *         &lt;element name="ImportControlIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LabelMethod" type="{}LabelMethodType" minOccurs="0"/&gt;
 *         &lt;element name="CommercialInvoiceRemovalIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UPScarbonneutralIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PreAlertNotification" type="{}PreAlertNotificationType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ExchangeForwardIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="HoldForPickupIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DropoffAtUPSFacilityIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LiftGateForPickUpIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LiftGateForDeliveryIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SDLShipmentIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EPRAReleaseCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RestrictedArticles" type="{}RestrictedArticlesType" minOccurs="0"/&gt;
 *         &lt;element name="InsideDelivery" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ItemDisposal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@NoArgsConstructor
@AllArgsConstructor
@Builder
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShipmentServiceOptionsType", propOrder = {
    "saturdayDelivery",
    "saturdayPickupIndicator",
    "cod",
    "accessPointCOD",
    "deliverToAddresseeOnlyIndicator",
    "directDeliveryOnlyIndicator",
    "notification",
    "labelDelivery",
    "internationalForms",
    "returnOfDocumentIndicator",
    "deliveryConfirmation",
    "importControlIndicator",
    "labelMethod",
    "commercialInvoiceRemovalIndicator",
    "upScarbonneutralIndicator",
    "preAlertNotification",
    "exchangeForwardIndicator",
    "holdForPickupIndicator",
    "dropoffAtUPSFacilityIndicator",
    "liftGateForPickUpIndicator",
    "liftGateForDeliveryIndicator",
    "sdlShipmentIndicator",
    "epraReleaseCode",
    "restrictedArticles",
    "insideDelivery",
    "itemDisposal"
})
public class ShipmentServiceOptionsType {

    @XmlElement(name = "SaturdayDelivery")
    protected String saturdayDelivery;
    @XmlElement(name = "SaturdayPickupIndicator")
    protected String saturdayPickupIndicator;
    @XmlElement(name = "COD")
    protected ShipmentServiceOptionsCODType cod;
    @XmlElement(name = "AccessPointCOD")
    protected ShipmentServiceOptionsAccessPointCODType accessPointCOD;
    @XmlElement(name = "DeliverToAddresseeOnlyIndicator")
    protected String deliverToAddresseeOnlyIndicator;
    @XmlElement(name = "DirectDeliveryOnlyIndicator")
    protected String directDeliveryOnlyIndicator;
    @XmlElement(name = "Notification")
    protected List<ShipmentServiceOptionsNotificationType> notification;
    @XmlElement(name = "LabelDelivery")
    protected LabelDeliveryType labelDelivery;
    @XmlElement(name = "InternationalForms")
    protected InternationalFormsType internationalForms;
    @XmlElement(name = "ReturnOfDocumentIndicator")
    protected String returnOfDocumentIndicator;
    @XmlElement(name = "DeliveryConfirmation")
    protected ShipmentServiceOptionsDeliveryConfirmationType deliveryConfirmation;
    @XmlElement(name = "ImportControlIndicator")
    protected String importControlIndicator;
    @XmlElement(name = "LabelMethod")
    protected LabelMethodType labelMethod;
    @XmlElement(name = "CommercialInvoiceRemovalIndicator")
    protected String commercialInvoiceRemovalIndicator;
    @XmlElement(name = "UPScarbonneutralIndicator")
    protected String upScarbonneutralIndicator;
    @XmlElement(name = "PreAlertNotification")
    protected List<PreAlertNotificationType> preAlertNotification;
    @XmlElement(name = "ExchangeForwardIndicator")
    protected String exchangeForwardIndicator;
    @XmlElement(name = "HoldForPickupIndicator")
    protected String holdForPickupIndicator;
    @XmlElement(name = "DropoffAtUPSFacilityIndicator")
    protected String dropoffAtUPSFacilityIndicator;
    @XmlElement(name = "LiftGateForPickUpIndicator")
    protected String liftGateForPickUpIndicator;
    @XmlElement(name = "LiftGateForDeliveryIndicator")
    protected String liftGateForDeliveryIndicator;
    @XmlElement(name = "SDLShipmentIndicator")
    protected String sdlShipmentIndicator;
    @XmlElement(name = "EPRAReleaseCode")
    protected String epraReleaseCode;
    @XmlElement(name = "RestrictedArticles")
    protected RestrictedArticlesType restrictedArticles;
    @XmlElement(name = "InsideDelivery")
    protected String insideDelivery;
    @XmlElement(name = "ItemDisposal")
    protected String itemDisposal;

    /**
     * Gets the value of the saturdayDelivery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSaturdayDelivery() {
        return saturdayDelivery;
    }

    /**
     * Sets the value of the saturdayDelivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSaturdayDelivery(String value) {
        this.saturdayDelivery = value;
    }

    /**
     * Gets the value of the saturdayPickupIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSaturdayPickupIndicator() {
        return saturdayPickupIndicator;
    }

    /**
     * Sets the value of the saturdayPickupIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSaturdayPickupIndicator(String value) {
        this.saturdayPickupIndicator = value;
    }

    /**
     * Gets the value of the cod property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentServiceOptionsCODType }
     *     
     */
    public ShipmentServiceOptionsCODType getCOD() {
        return cod;
    }

    /**
     * Sets the value of the cod property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentServiceOptionsCODType }
     *     
     */
    public void setCOD(ShipmentServiceOptionsCODType value) {
        this.cod = value;
    }

    /**
     * Gets the value of the accessPointCOD property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentServiceOptionsAccessPointCODType }
     *     
     */
    public ShipmentServiceOptionsAccessPointCODType getAccessPointCOD() {
        return accessPointCOD;
    }

    /**
     * Sets the value of the accessPointCOD property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentServiceOptionsAccessPointCODType }
     *     
     */
    public void setAccessPointCOD(ShipmentServiceOptionsAccessPointCODType value) {
        this.accessPointCOD = value;
    }

    /**
     * Gets the value of the deliverToAddresseeOnlyIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliverToAddresseeOnlyIndicator() {
        return deliverToAddresseeOnlyIndicator;
    }

    /**
     * Sets the value of the deliverToAddresseeOnlyIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliverToAddresseeOnlyIndicator(String value) {
        this.deliverToAddresseeOnlyIndicator = value;
    }

    /**
     * Gets the value of the directDeliveryOnlyIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectDeliveryOnlyIndicator() {
        return directDeliveryOnlyIndicator;
    }

    /**
     * Sets the value of the directDeliveryOnlyIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectDeliveryOnlyIndicator(String value) {
        this.directDeliveryOnlyIndicator = value;
    }

    /**
     * Gets the value of the notification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the notification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNotification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ShipmentServiceOptionsNotificationType }
     * 
     * 
     */
    public List<ShipmentServiceOptionsNotificationType> getNotification() {
        if (notification == null) {
            notification = new ArrayList<ShipmentServiceOptionsNotificationType>();
        }
        return this.notification;
    }

    /**
     * Gets the value of the labelDelivery property.
     * 
     * @return
     *     possible object is
     *     {@link LabelDeliveryType }
     *     
     */
    public LabelDeliveryType getLabelDelivery() {
        return labelDelivery;
    }

    /**
     * Sets the value of the labelDelivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelDeliveryType }
     *     
     */
    public void setLabelDelivery(LabelDeliveryType value) {
        this.labelDelivery = value;
    }

    /**
     * Gets the value of the internationalForms property.
     * 
     * @return
     *     possible object is
     *     {@link InternationalFormsType }
     *     
     */
    public InternationalFormsType getInternationalForms() {
        return internationalForms;
    }

    /**
     * Sets the value of the internationalForms property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternationalFormsType }
     *     
     */
    public void setInternationalForms(InternationalFormsType value) {
        this.internationalForms = value;
    }

    /**
     * Gets the value of the returnOfDocumentIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnOfDocumentIndicator() {
        return returnOfDocumentIndicator;
    }

    /**
     * Sets the value of the returnOfDocumentIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnOfDocumentIndicator(String value) {
        this.returnOfDocumentIndicator = value;
    }

    /**
     * Gets the value of the deliveryConfirmation property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentServiceOptionsDeliveryConfirmationType }
     *     
     */
    public ShipmentServiceOptionsDeliveryConfirmationType getDeliveryConfirmation() {
        return deliveryConfirmation;
    }

    /**
     * Sets the value of the deliveryConfirmation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentServiceOptionsDeliveryConfirmationType }
     *     
     */
    public void setDeliveryConfirmation(ShipmentServiceOptionsDeliveryConfirmationType value) {
        this.deliveryConfirmation = value;
    }

    /**
     * Gets the value of the importControlIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportControlIndicator() {
        return importControlIndicator;
    }

    /**
     * Sets the value of the importControlIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportControlIndicator(String value) {
        this.importControlIndicator = value;
    }

    /**
     * Gets the value of the labelMethod property.
     * 
     * @return
     *     possible object is
     *     {@link LabelMethodType }
     *     
     */
    public LabelMethodType getLabelMethod() {
        return labelMethod;
    }

    /**
     * Sets the value of the labelMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelMethodType }
     *     
     */
    public void setLabelMethod(LabelMethodType value) {
        this.labelMethod = value;
    }

    /**
     * Gets the value of the commercialInvoiceRemovalIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommercialInvoiceRemovalIndicator() {
        return commercialInvoiceRemovalIndicator;
    }

    /**
     * Sets the value of the commercialInvoiceRemovalIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommercialInvoiceRemovalIndicator(String value) {
        this.commercialInvoiceRemovalIndicator = value;
    }

    /**
     * Gets the value of the upScarbonneutralIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUPScarbonneutralIndicator() {
        return upScarbonneutralIndicator;
    }

    /**
     * Sets the value of the upScarbonneutralIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUPScarbonneutralIndicator(String value) {
        this.upScarbonneutralIndicator = value;
    }

    /**
     * Gets the value of the preAlertNotification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the preAlertNotification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPreAlertNotification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PreAlertNotificationType }
     * 
     * 
     */
    public List<PreAlertNotificationType> getPreAlertNotification() {
        if (preAlertNotification == null) {
            preAlertNotification = new ArrayList<PreAlertNotificationType>();
        }
        return this.preAlertNotification;
    }

    /**
     * Gets the value of the exchangeForwardIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExchangeForwardIndicator() {
        return exchangeForwardIndicator;
    }

    /**
     * Sets the value of the exchangeForwardIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExchangeForwardIndicator(String value) {
        this.exchangeForwardIndicator = value;
    }

    /**
     * Gets the value of the holdForPickupIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoldForPickupIndicator() {
        return holdForPickupIndicator;
    }

    /**
     * Sets the value of the holdForPickupIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoldForPickupIndicator(String value) {
        this.holdForPickupIndicator = value;
    }

    /**
     * Gets the value of the dropoffAtUPSFacilityIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDropoffAtUPSFacilityIndicator() {
        return dropoffAtUPSFacilityIndicator;
    }

    /**
     * Sets the value of the dropoffAtUPSFacilityIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDropoffAtUPSFacilityIndicator(String value) {
        this.dropoffAtUPSFacilityIndicator = value;
    }

    /**
     * Gets the value of the liftGateForPickUpIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLiftGateForPickUpIndicator() {
        return liftGateForPickUpIndicator;
    }

    /**
     * Sets the value of the liftGateForPickUpIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLiftGateForPickUpIndicator(String value) {
        this.liftGateForPickUpIndicator = value;
    }

    /**
     * Gets the value of the liftGateForDeliveryIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLiftGateForDeliveryIndicator() {
        return liftGateForDeliveryIndicator;
    }

    /**
     * Sets the value of the liftGateForDeliveryIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLiftGateForDeliveryIndicator(String value) {
        this.liftGateForDeliveryIndicator = value;
    }

    /**
     * Gets the value of the sdlShipmentIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSDLShipmentIndicator() {
        return sdlShipmentIndicator;
    }

    /**
     * Sets the value of the sdlShipmentIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSDLShipmentIndicator(String value) {
        this.sdlShipmentIndicator = value;
    }

    /**
     * Gets the value of the epraReleaseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEPRAReleaseCode() {
        return epraReleaseCode;
    }

    /**
     * Sets the value of the epraReleaseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEPRAReleaseCode(String value) {
        this.epraReleaseCode = value;
    }

    /**
     * Gets the value of the restrictedArticles property.
     * 
     * @return
     *     possible object is
     *     {@link RestrictedArticlesType }
     *     
     */
    public RestrictedArticlesType getRestrictedArticles() {
        return restrictedArticles;
    }

    /**
     * Sets the value of the restrictedArticles property.
     * 
     * @param value
     *     allowed object is
     *     {@link RestrictedArticlesType }
     *     
     */
    public void setRestrictedArticles(RestrictedArticlesType value) {
        this.restrictedArticles = value;
    }

    /**
     * Gets the value of the insideDelivery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsideDelivery() {
        return insideDelivery;
    }

    /**
     * Sets the value of the insideDelivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsideDelivery(String value) {
        this.insideDelivery = value;
    }

    /**
     * Gets the value of the itemDisposal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemDisposal() {
        return itemDisposal;
    }

    /**
     * Sets the value of the itemDisposal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemDisposal(String value) {
        this.itemDisposal = value;
    }

}
