//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.11 at 06:23:24 PM KST 
//


package com.ups.shipping.shipconfirmrequest;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ShipmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShipmentType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReturnService" type="{}ReturnServiceType" minOccurs="0"/&gt;
 *         &lt;element name="DocumentsOnly" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Shipper" type="{}ShipperType"/&gt;
 *         &lt;element name="ShipTo" type="{}ShipToType"/&gt;
 *         &lt;element name="AlternateDeliveryAddress" type="{}AlternateDeliveryAddressType" minOccurs="0"/&gt;
 *         &lt;element name="ShipFrom" type="{}ShipFromType" minOccurs="0"/&gt;
 *         &lt;element name="SoldTo" type="{}SoldToType" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="PaymentInformation" type="{}PaymentInformationType" minOccurs="0"/&gt;
 *           &lt;element name="ItemizedPaymentInformation" type="{}ItemizedPaymentInformationType" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="GoodsNotInFreeCirculationIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RateInformation" type="{}RateInformationType" minOccurs="0"/&gt;
 *         &lt;element name="MovementReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReferenceNumber" type="{}ReferenceNumberType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Service" type="{}ServiceType"/&gt;
 *         &lt;element name="InvoiceLineTotal" type="{}InvoiceLineTotalType" minOccurs="0"/&gt;
 *         &lt;element name="NumOfPiecesInShipment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="USPSEndorsement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MILabelCN22Indicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SubClassification" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CostCenter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CostCenterBarcodeIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PackageID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PackageIDBarcodeIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IrregularIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ShipmentServiceOptions" type="{}ShipmentServiceOptionsType" minOccurs="0"/&gt;
 *         &lt;element name="Package" type="{}PackageType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="MIDualReturnShipmentKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MIDualReturnShipmentIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RatingMethodRequestedIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TaxInformationIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ShipmentIndicationType" type="{}IndicationType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="PromotionalDiscountInformation" type="{}PromotionalDiscountInformationType" minOccurs="0"/&gt;
 *         &lt;element name="DGSignatoryInfo" type="{}DGSignatoryInfoType" minOccurs="0"/&gt;
 *         &lt;element name="MasterCartonID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MasterCartonIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@NoArgsConstructor
@AllArgsConstructor
@Builder
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShipmentType", propOrder = {
    "description",
    "returnService",
    "documentsOnly",
    "shipper",
    "shipTo",
    "alternateDeliveryAddress",
    "shipFrom",
    "soldTo",
    "paymentInformation",
    "itemizedPaymentInformation",
    "goodsNotInFreeCirculationIndicator",
    "rateInformation",
    "movementReferenceNumber",
    "referenceNumber",
    "service",
    "invoiceLineTotal",
    "numOfPiecesInShipment",
    "uspsEndorsement",
    "miLabelCN22Indicator",
    "subClassification",
    "costCenter",
    "costCenterBarcodeIndicator",
    "packageID",
    "packageIDBarcodeIndicator",
    "irregularIndicator",
    "shipmentServiceOptions",
    "_package",
    "miDualReturnShipmentKey",
    "miDualReturnShipmentIndicator",
    "ratingMethodRequestedIndicator",
    "taxInformationIndicator",
    "shipmentIndicationType",
    "promotionalDiscountInformation",
    "dgSignatoryInfo",
    "masterCartonID",
    "masterCartonIndicator"
})
public class ShipmentType {

    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "ReturnService")
    protected ReturnServiceType returnService;
    @XmlElement(name = "DocumentsOnly")
    protected String documentsOnly;
    @XmlElement(name = "Shipper", required = true)
    protected ShipperType shipper;
    @XmlElement(name = "ShipTo", required = true)
    protected ShipToType shipTo;
    @XmlElement(name = "AlternateDeliveryAddress")
    protected AlternateDeliveryAddressType alternateDeliveryAddress;
    @XmlElement(name = "ShipFrom")
    protected ShipFromType shipFrom;
    @XmlElement(name = "SoldTo")
    protected SoldToType soldTo;
    @XmlElement(name = "PaymentInformation")
    protected PaymentInformationType paymentInformation;
    @XmlElement(name = "ItemizedPaymentInformation")
    protected ItemizedPaymentInformationType itemizedPaymentInformation;
    @XmlElement(name = "GoodsNotInFreeCirculationIndicator")
    protected String goodsNotInFreeCirculationIndicator;
    @XmlElement(name = "RateInformation")
    protected RateInformationType rateInformation;
    @XmlElement(name = "MovementReferenceNumber")
    protected String movementReferenceNumber;
    @XmlElement(name = "ReferenceNumber")
    protected List<ReferenceNumberType> referenceNumber;
    @XmlElement(name = "Service", required = true)
    protected ServiceType service;
    @XmlElement(name = "InvoiceLineTotal")
    protected InvoiceLineTotalType invoiceLineTotal;
    @XmlElement(name = "NumOfPiecesInShipment")
    protected String numOfPiecesInShipment;
    @XmlElement(name = "USPSEndorsement")
    protected String uspsEndorsement;
    @XmlElement(name = "MILabelCN22Indicator")
    protected String miLabelCN22Indicator;
    @XmlElement(name = "SubClassification")
    protected String subClassification;
    @XmlElement(name = "CostCenter")
    protected String costCenter;
    @XmlElement(name = "CostCenterBarcodeIndicator")
    protected String costCenterBarcodeIndicator;
    @XmlElement(name = "PackageID")
    protected String packageID;
    @XmlElement(name = "PackageIDBarcodeIndicator")
    protected String packageIDBarcodeIndicator;
    @XmlElement(name = "IrregularIndicator")
    protected String irregularIndicator;
    @XmlElement(name = "ShipmentServiceOptions")
    protected ShipmentServiceOptionsType shipmentServiceOptions;
    @XmlElement(name = "Package", required = true)
    protected List<PackageType> _package;
    @XmlElement(name = "MIDualReturnShipmentKey")
    protected String miDualReturnShipmentKey;
    @XmlElement(name = "MIDualReturnShipmentIndicator")
    protected String miDualReturnShipmentIndicator;
    @XmlElement(name = "RatingMethodRequestedIndicator")
    protected String ratingMethodRequestedIndicator;
    @XmlElement(name = "TaxInformationIndicator")
    protected String taxInformationIndicator;
    @XmlElement(name = "ShipmentIndicationType")
    protected List<IndicationType> shipmentIndicationType;
    @XmlElement(name = "PromotionalDiscountInformation")
    protected PromotionalDiscountInformationType promotionalDiscountInformation;
    @XmlElement(name = "DGSignatoryInfo")
    protected DGSignatoryInfoType dgSignatoryInfo;
    @XmlElement(name = "MasterCartonID")
    protected String masterCartonID;
    @XmlElement(name = "MasterCartonIndicator")
    protected String masterCartonIndicator;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the returnService property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnServiceType }
     *     
     */
    public ReturnServiceType getReturnService() {
        return returnService;
    }

    /**
     * Sets the value of the returnService property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnServiceType }
     *     
     */
    public void setReturnService(ReturnServiceType value) {
        this.returnService = value;
    }

    /**
     * Gets the value of the documentsOnly property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentsOnly() {
        return documentsOnly;
    }

    /**
     * Sets the value of the documentsOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentsOnly(String value) {
        this.documentsOnly = value;
    }

    /**
     * Gets the value of the shipper property.
     * 
     * @return
     *     possible object is
     *     {@link ShipperType }
     *     
     */
    public ShipperType getShipper() {
        return shipper;
    }

    /**
     * Sets the value of the shipper property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipperType }
     *     
     */
    public void setShipper(ShipperType value) {
        this.shipper = value;
    }

    /**
     * Gets the value of the shipTo property.
     * 
     * @return
     *     possible object is
     *     {@link ShipToType }
     *     
     */
    public ShipToType getShipTo() {
        return shipTo;
    }

    /**
     * Sets the value of the shipTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipToType }
     *     
     */
    public void setShipTo(ShipToType value) {
        this.shipTo = value;
    }

    /**
     * Gets the value of the alternateDeliveryAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AlternateDeliveryAddressType }
     *     
     */
    public AlternateDeliveryAddressType getAlternateDeliveryAddress() {
        return alternateDeliveryAddress;
    }

    /**
     * Sets the value of the alternateDeliveryAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlternateDeliveryAddressType }
     *     
     */
    public void setAlternateDeliveryAddress(AlternateDeliveryAddressType value) {
        this.alternateDeliveryAddress = value;
    }

    /**
     * Gets the value of the shipFrom property.
     * 
     * @return
     *     possible object is
     *     {@link ShipFromType }
     *     
     */
    public ShipFromType getShipFrom() {
        return shipFrom;
    }

    /**
     * Sets the value of the shipFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipFromType }
     *     
     */
    public void setShipFrom(ShipFromType value) {
        this.shipFrom = value;
    }

    /**
     * Gets the value of the soldTo property.
     * 
     * @return
     *     possible object is
     *     {@link SoldToType }
     *     
     */
    public SoldToType getSoldTo() {
        return soldTo;
    }

    /**
     * Sets the value of the soldTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoldToType }
     *     
     */
    public void setSoldTo(SoldToType value) {
        this.soldTo = value;
    }

    /**
     * Gets the value of the paymentInformation property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentInformationType }
     *     
     */
    public PaymentInformationType getPaymentInformation() {
        return paymentInformation;
    }

    /**
     * Sets the value of the paymentInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentInformationType }
     *     
     */
    public void setPaymentInformation(PaymentInformationType value) {
        this.paymentInformation = value;
    }

    /**
     * Gets the value of the itemizedPaymentInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ItemizedPaymentInformationType }
     *     
     */
    public ItemizedPaymentInformationType getItemizedPaymentInformation() {
        return itemizedPaymentInformation;
    }

    /**
     * Sets the value of the itemizedPaymentInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemizedPaymentInformationType }
     *     
     */
    public void setItemizedPaymentInformation(ItemizedPaymentInformationType value) {
        this.itemizedPaymentInformation = value;
    }

    /**
     * Gets the value of the goodsNotInFreeCirculationIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGoodsNotInFreeCirculationIndicator() {
        return goodsNotInFreeCirculationIndicator;
    }

    /**
     * Sets the value of the goodsNotInFreeCirculationIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGoodsNotInFreeCirculationIndicator(String value) {
        this.goodsNotInFreeCirculationIndicator = value;
    }

    /**
     * Gets the value of the rateInformation property.
     * 
     * @return
     *     possible object is
     *     {@link RateInformationType }
     *     
     */
    public RateInformationType getRateInformation() {
        return rateInformation;
    }

    /**
     * Sets the value of the rateInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link RateInformationType }
     *     
     */
    public void setRateInformation(RateInformationType value) {
        this.rateInformation = value;
    }

    /**
     * Gets the value of the movementReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMovementReferenceNumber() {
        return movementReferenceNumber;
    }

    /**
     * Sets the value of the movementReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMovementReferenceNumber(String value) {
        this.movementReferenceNumber = value;
    }

    /**
     * Gets the value of the referenceNumber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referenceNumber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferenceNumber().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReferenceNumberType }
     * 
     * 
     */
    public List<ReferenceNumberType> getReferenceNumber() {
        if (referenceNumber == null) {
            referenceNumber = new ArrayList<ReferenceNumberType>();
        }
        return this.referenceNumber;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceType }
     *     
     */
    public ServiceType getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceType }
     *     
     */
    public void setService(ServiceType value) {
        this.service = value;
    }

    /**
     * Gets the value of the invoiceLineTotal property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceLineTotalType }
     *     
     */
    public InvoiceLineTotalType getInvoiceLineTotal() {
        return invoiceLineTotal;
    }

    /**
     * Sets the value of the invoiceLineTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceLineTotalType }
     *     
     */
    public void setInvoiceLineTotal(InvoiceLineTotalType value) {
        this.invoiceLineTotal = value;
    }

    /**
     * Gets the value of the numOfPiecesInShipment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumOfPiecesInShipment() {
        return numOfPiecesInShipment;
    }

    /**
     * Sets the value of the numOfPiecesInShipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumOfPiecesInShipment(String value) {
        this.numOfPiecesInShipment = value;
    }

    /**
     * Gets the value of the uspsEndorsement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSPSEndorsement() {
        return uspsEndorsement;
    }

    /**
     * Sets the value of the uspsEndorsement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSPSEndorsement(String value) {
        this.uspsEndorsement = value;
    }

    /**
     * Gets the value of the miLabelCN22Indicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMILabelCN22Indicator() {
        return miLabelCN22Indicator;
    }

    /**
     * Sets the value of the miLabelCN22Indicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMILabelCN22Indicator(String value) {
        this.miLabelCN22Indicator = value;
    }

    /**
     * Gets the value of the subClassification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubClassification() {
        return subClassification;
    }

    /**
     * Sets the value of the subClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubClassification(String value) {
        this.subClassification = value;
    }

    /**
     * Gets the value of the costCenter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostCenter() {
        return costCenter;
    }

    /**
     * Sets the value of the costCenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostCenter(String value) {
        this.costCenter = value;
    }

    /**
     * Gets the value of the costCenterBarcodeIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostCenterBarcodeIndicator() {
        return costCenterBarcodeIndicator;
    }

    /**
     * Sets the value of the costCenterBarcodeIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostCenterBarcodeIndicator(String value) {
        this.costCenterBarcodeIndicator = value;
    }

    /**
     * Gets the value of the packageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackageID() {
        return packageID;
    }

    /**
     * Sets the value of the packageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackageID(String value) {
        this.packageID = value;
    }

    /**
     * Gets the value of the packageIDBarcodeIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackageIDBarcodeIndicator() {
        return packageIDBarcodeIndicator;
    }

    /**
     * Sets the value of the packageIDBarcodeIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackageIDBarcodeIndicator(String value) {
        this.packageIDBarcodeIndicator = value;
    }

    /**
     * Gets the value of the irregularIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIrregularIndicator() {
        return irregularIndicator;
    }

    /**
     * Sets the value of the irregularIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIrregularIndicator(String value) {
        this.irregularIndicator = value;
    }

    /**
     * Gets the value of the shipmentServiceOptions property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentServiceOptionsType }
     *     
     */
    public ShipmentServiceOptionsType getShipmentServiceOptions() {
        return shipmentServiceOptions;
    }

    /**
     * Sets the value of the shipmentServiceOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentServiceOptionsType }
     *     
     */
    public void setShipmentServiceOptions(ShipmentServiceOptionsType value) {
        this.shipmentServiceOptions = value;
    }

    /**
     * Gets the value of the package property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the package property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPackage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PackageType }
     * 
     * 
     */
    public List<PackageType> getPackage() {
        if (_package == null) {
            _package = new ArrayList<PackageType>();
        }
        return this._package;
    }

    /**
     * Gets the value of the miDualReturnShipmentKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMIDualReturnShipmentKey() {
        return miDualReturnShipmentKey;
    }

    /**
     * Sets the value of the miDualReturnShipmentKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMIDualReturnShipmentKey(String value) {
        this.miDualReturnShipmentKey = value;
    }

    /**
     * Gets the value of the miDualReturnShipmentIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMIDualReturnShipmentIndicator() {
        return miDualReturnShipmentIndicator;
    }

    /**
     * Sets the value of the miDualReturnShipmentIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMIDualReturnShipmentIndicator(String value) {
        this.miDualReturnShipmentIndicator = value;
    }

    /**
     * Gets the value of the ratingMethodRequestedIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRatingMethodRequestedIndicator() {
        return ratingMethodRequestedIndicator;
    }

    /**
     * Sets the value of the ratingMethodRequestedIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRatingMethodRequestedIndicator(String value) {
        this.ratingMethodRequestedIndicator = value;
    }

    /**
     * Gets the value of the taxInformationIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxInformationIndicator() {
        return taxInformationIndicator;
    }

    /**
     * Sets the value of the taxInformationIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxInformationIndicator(String value) {
        this.taxInformationIndicator = value;
    }

    /**
     * Gets the value of the shipmentIndicationType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shipmentIndicationType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShipmentIndicationType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IndicationType }
     * 
     * 
     */
    public List<IndicationType> getShipmentIndicationType() {
        if (shipmentIndicationType == null) {
            shipmentIndicationType = new ArrayList<IndicationType>();
        }
        return this.shipmentIndicationType;
    }

    /**
     * Gets the value of the promotionalDiscountInformation property.
     * 
     * @return
     *     possible object is
     *     {@link PromotionalDiscountInformationType }
     *     
     */
    public PromotionalDiscountInformationType getPromotionalDiscountInformation() {
        return promotionalDiscountInformation;
    }

    /**
     * Sets the value of the promotionalDiscountInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PromotionalDiscountInformationType }
     *     
     */
    public void setPromotionalDiscountInformation(PromotionalDiscountInformationType value) {
        this.promotionalDiscountInformation = value;
    }

    /**
     * Gets the value of the dgSignatoryInfo property.
     * 
     * @return
     *     possible object is
     *     {@link DGSignatoryInfoType }
     *     
     */
    public DGSignatoryInfoType getDGSignatoryInfo() {
        return dgSignatoryInfo;
    }

    /**
     * Sets the value of the dgSignatoryInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DGSignatoryInfoType }
     *     
     */
    public void setDGSignatoryInfo(DGSignatoryInfoType value) {
        this.dgSignatoryInfo = value;
    }

    /**
     * Gets the value of the masterCartonID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasterCartonID() {
        return masterCartonID;
    }

    /**
     * Sets the value of the masterCartonID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasterCartonID(String value) {
        this.masterCartonID = value;
    }

    /**
     * Gets the value of the masterCartonIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasterCartonIndicator() {
        return masterCartonIndicator;
    }

    /**
     * Sets the value of the masterCartonIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasterCartonIndicator(String value) {
        this.masterCartonIndicator = value;
    }

}
