//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.11 at 06:08:30 PM KST 
//


package com.ups.shipping.ifs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UltimateConsigneeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UltimateConsigneeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}CompanyName" minOccurs="0"/&gt;
 *         &lt;element name="Address" type="{}AddressType" minOccurs="0"/&gt;
 *         &lt;element name="UltimateConsigneeType" type="{}UltimateConsigneeTypeType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UltimateConsigneeType", propOrder = {
    "companyName",
    "address",
    "ultimateConsigneeType"
})
public class UltimateConsigneeType {

    @XmlElement(name = "CompanyName")
    protected String companyName;
    @XmlElement(name = "Address")
    protected AddressType address;
    @XmlElement(name = "UltimateConsigneeType")
    protected UltimateConsigneeTypeType ultimateConsigneeType;

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setAddress(AddressType value) {
        this.address = value;
    }

    /**
     * Gets the value of the ultimateConsigneeType property.
     * 
     * @return
     *     possible object is
     *     {@link UltimateConsigneeTypeType }
     *     
     */
    public UltimateConsigneeTypeType getUltimateConsigneeType() {
        return ultimateConsigneeType;
    }

    /**
     * Sets the value of the ultimateConsigneeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link UltimateConsigneeTypeType }
     *     
     */
    public void setUltimateConsigneeType(UltimateConsigneeTypeType value) {
        this.ultimateConsigneeType = value;
    }

}
