//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.11 at 06:09:38 PM KST 
//


package com.ups.shipping.labelrecoveryresponse;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Response"/&gt;
 *         &lt;element name="ShipmentIdentificationNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CODTurnInPage" type="{}CODTurnInPageType" minOccurs="0"/&gt;
 *         &lt;element name="Form" type="{}FormType" minOccurs="0"/&gt;
 *         &lt;element name="HighValueReport" type="{}HighValueReportType" minOccurs="0"/&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element name="LabelResults" type="{}LabelResultsType"/&gt;
 *           &lt;element name="TrackingCandidate" type="{}TrackingCandidateType"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "response",
    "shipmentIdentificationNumber",
    "codTurnInPage",
    "form",
    "highValueReport",
    "labelResultsOrTrackingCandidate"
})
@XmlRootElement(name = "LabelRecoveryResponse")
public class LabelRecoveryResponse {

    @XmlElement(name = "Response", required = true)
    protected Response response;
    @XmlElement(name = "ShipmentIdentificationNumber")
    protected String shipmentIdentificationNumber;
    @XmlElement(name = "CODTurnInPage")
    protected CODTurnInPageType codTurnInPage;
    @XmlElement(name = "Form")
    protected FormType form;
    @XmlElement(name = "HighValueReport")
    protected HighValueReportType highValueReport;
    @XmlElements({
        @XmlElement(name = "LabelResults", type = LabelResultsType.class),
        @XmlElement(name = "TrackingCandidate", type = TrackingCandidateType.class)
    })
    protected List<Object> labelResultsOrTrackingCandidate;

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link Response }
     *     
     */
    public Response getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response }
     *     
     */
    public void setResponse(Response value) {
        this.response = value;
    }

    /**
     * Gets the value of the shipmentIdentificationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipmentIdentificationNumber() {
        return shipmentIdentificationNumber;
    }

    /**
     * Sets the value of the shipmentIdentificationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipmentIdentificationNumber(String value) {
        this.shipmentIdentificationNumber = value;
    }

    /**
     * Gets the value of the codTurnInPage property.
     * 
     * @return
     *     possible object is
     *     {@link CODTurnInPageType }
     *     
     */
    public CODTurnInPageType getCODTurnInPage() {
        return codTurnInPage;
    }

    /**
     * Sets the value of the codTurnInPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODTurnInPageType }
     *     
     */
    public void setCODTurnInPage(CODTurnInPageType value) {
        this.codTurnInPage = value;
    }

    /**
     * Gets the value of the form property.
     * 
     * @return
     *     possible object is
     *     {@link FormType }
     *     
     */
    public FormType getForm() {
        return form;
    }

    /**
     * Sets the value of the form property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormType }
     *     
     */
    public void setForm(FormType value) {
        this.form = value;
    }

    /**
     * Gets the value of the highValueReport property.
     * 
     * @return
     *     possible object is
     *     {@link HighValueReportType }
     *     
     */
    public HighValueReportType getHighValueReport() {
        return highValueReport;
    }

    /**
     * Sets the value of the highValueReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link HighValueReportType }
     *     
     */
    public void setHighValueReport(HighValueReportType value) {
        this.highValueReport = value;
    }

    /**
     * Gets the value of the labelResultsOrTrackingCandidate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the labelResultsOrTrackingCandidate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabelResultsOrTrackingCandidate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LabelResultsType }
     * {@link TrackingCandidateType }
     * 
     * 
     */
    public List<Object> getLabelResultsOrTrackingCandidate() {
        if (labelResultsOrTrackingCandidate == null) {
            labelResultsOrTrackingCandidate = new ArrayList<Object>();
        }
        return this.labelResultsOrTrackingCandidate;
    }

}
