//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.11 at 06:09:38 PM KST 
//


package com.ups.shipping.labelrecoveryresponse;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ups.shipping.labelrecoveryresponse package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ups.shipping.labelrecoveryresponse
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LabelRecoveryResponse }
     * 
     */
    public LabelRecoveryResponse createLabelRecoveryResponse() {
        return new LabelRecoveryResponse();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link TransactionReference }
     * 
     */
    public TransactionReference createTransactionReference() {
        return new TransactionReference();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link ErrorLocation }
     * 
     */
    public ErrorLocation createErrorLocation() {
        return new ErrorLocation();
    }

    /**
     * Create an instance of {@link CODTurnInPageType }
     * 
     */
    public CODTurnInPageType createCODTurnInPageType() {
        return new CODTurnInPageType();
    }

    /**
     * Create an instance of {@link FormType }
     * 
     */
    public FormType createFormType() {
        return new FormType();
    }

    /**
     * Create an instance of {@link HighValueReportType }
     * 
     */
    public HighValueReportType createHighValueReportType() {
        return new HighValueReportType();
    }

    /**
     * Create an instance of {@link LabelResultsType }
     * 
     */
    public LabelResultsType createLabelResultsType() {
        return new LabelResultsType();
    }

    /**
     * Create an instance of {@link TrackingCandidateType }
     * 
     */
    public TrackingCandidateType createTrackingCandidateType() {
        return new TrackingCandidateType();
    }

    /**
     * Create an instance of {@link LabelImageType }
     * 
     */
    public LabelImageType createLabelImageType() {
        return new LabelImageType();
    }

    /**
     * Create an instance of {@link ReceiptType }
     * 
     */
    public ReceiptType createReceiptType() {
        return new ReceiptType();
    }

    /**
     * Create an instance of {@link ImageType }
     * 
     */
    public ImageType createImageType() {
        return new ImageType();
    }

    /**
     * Create an instance of {@link CodeType }
     * 
     */
    public CodeType createCodeType() {
        return new CodeType();
    }

    /**
     * Create an instance of {@link PickupDateRangeType }
     * 
     */
    public PickupDateRangeType createPickupDateRangeType() {
        return new PickupDateRangeType();
    }

    /**
     * Create an instance of {@link ImageType2 }
     * 
     */
    public ImageType2 createImageType2() {
        return new ImageType2();
    }

    /**
     * Create an instance of {@link LabelImageFormatType2 }
     * 
     */
    public LabelImageFormatType2 createLabelImageFormatType2() {
        return new LabelImageFormatType2();
    }

    /**
     * Create an instance of {@link FormImageType }
     * 
     */
    public FormImageType createFormImageType() {
        return new FormImageType();
    }

    /**
     * Create an instance of {@link HVRImageType }
     * 
     */
    public HVRImageType createHVRImageType() {
        return new HVRImageType();
    }

}
