//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.11 at 06:09:13 PM KST 
//


package com.ups.shipping.labelrecoveryrequest;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Request"/&gt;
 *         &lt;element name="LabelSpecification" type="{}LabelSpecificationType" minOccurs="0"/&gt;
 *         &lt;element name="Translate" type="{}TranslateType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="LabelDelivery" type="{}LabelDeliveryType" minOccurs="0"/&gt;
 *         &lt;element name="MailInnovationsTrackingNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UPSPremiumCareForm" type="{}LRUPSPremiumCareFormType" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="TrackingNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;sequence&gt;
 *             &lt;element name="ReferenceNumber" type="{}ReferenceNumberType"/&gt;
 *             &lt;element name="ShipperNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;/sequence&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@NoArgsConstructor
@AllArgsConstructor
@Builder
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "request",
    "labelSpecification",
    "translate",
    "labelDelivery",
    "mailInnovationsTrackingNumber",
    "upsPremiumCareForm",
    "trackingNumber",
    "referenceNumber",
    "shipperNumber"
})
@XmlRootElement(name = "LabelRecoveryRequest")
public class LabelRecoveryRequest {

    @XmlElement(name = "Request", required = true)
    protected Request request;
    @XmlElement(name = "LabelSpecification")
    protected LabelSpecificationType labelSpecification;
    @XmlElement(name = "Translate")
    protected List<TranslateType> translate;
    @XmlElement(name = "LabelDelivery")
    protected LabelDeliveryType labelDelivery;
    @XmlElement(name = "MailInnovationsTrackingNumber")
    protected String mailInnovationsTrackingNumber;
    @XmlElement(name = "UPSPremiumCareForm")
    protected LRUPSPremiumCareFormType upsPremiumCareForm;
    @XmlElement(name = "TrackingNumber")
    protected String trackingNumber;
    @XmlElement(name = "ReferenceNumber")
    protected ReferenceNumberType referenceNumber;
    @XmlElement(name = "ShipperNumber")
    protected String shipperNumber;

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link Request }
     *     
     */
    public Request getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link Request }
     *     
     */
    public void setRequest(Request value) {
        this.request = value;
    }

    /**
     * Gets the value of the labelSpecification property.
     * 
     * @return
     *     possible object is
     *     {@link LabelSpecificationType }
     *     
     */
    public LabelSpecificationType getLabelSpecification() {
        return labelSpecification;
    }

    /**
     * Sets the value of the labelSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelSpecificationType }
     *     
     */
    public void setLabelSpecification(LabelSpecificationType value) {
        this.labelSpecification = value;
    }

    /**
     * Gets the value of the translate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the translate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTranslate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TranslateType }
     * 
     * 
     */
    public List<TranslateType> getTranslate() {
        if (translate == null) {
            translate = new ArrayList<TranslateType>();
        }
        return this.translate;
    }

    /**
     * Gets the value of the labelDelivery property.
     * 
     * @return
     *     possible object is
     *     {@link LabelDeliveryType }
     *     
     */
    public LabelDeliveryType getLabelDelivery() {
        return labelDelivery;
    }

    /**
     * Sets the value of the labelDelivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelDeliveryType }
     *     
     */
    public void setLabelDelivery(LabelDeliveryType value) {
        this.labelDelivery = value;
    }

    /**
     * Gets the value of the mailInnovationsTrackingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailInnovationsTrackingNumber() {
        return mailInnovationsTrackingNumber;
    }

    /**
     * Sets the value of the mailInnovationsTrackingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailInnovationsTrackingNumber(String value) {
        this.mailInnovationsTrackingNumber = value;
    }

    /**
     * Gets the value of the upsPremiumCareForm property.
     * 
     * @return
     *     possible object is
     *     {@link LRUPSPremiumCareFormType }
     *     
     */
    public LRUPSPremiumCareFormType getUPSPremiumCareForm() {
        return upsPremiumCareForm;
    }

    /**
     * Sets the value of the upsPremiumCareForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link LRUPSPremiumCareFormType }
     *     
     */
    public void setUPSPremiumCareForm(LRUPSPremiumCareFormType value) {
        this.upsPremiumCareForm = value;
    }

    /**
     * Gets the value of the trackingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackingNumber() {
        return trackingNumber;
    }

    /**
     * Sets the value of the trackingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackingNumber(String value) {
        this.trackingNumber = value;
    }

    /**
     * Gets the value of the referenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceNumberType }
     *     
     */
    public ReferenceNumberType getReferenceNumber() {
        return referenceNumber;
    }

    /**
     * Sets the value of the referenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceNumberType }
     *     
     */
    public void setReferenceNumber(ReferenceNumberType value) {
        this.referenceNumber = value;
    }

    /**
     * Gets the value of the shipperNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipperNumber() {
        return shipperNumber;
    }

    /**
     * Sets the value of the shipperNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipperNumber(String value) {
        this.shipperNumber = value;
    }

}
