//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.11 at 06:09:13 PM KST 
//


package com.ups.shipping.labelrecoveryrequest;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ups.shipping.labelrecoveryrequest package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ups.shipping.labelrecoveryrequest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LabelRecoveryRequest }
     * 
     */
    public LabelRecoveryRequest createLabelRecoveryRequest() {
        return new LabelRecoveryRequest();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link TransactionReference }
     * 
     */
    public TransactionReference createTransactionReference() {
        return new TransactionReference();
    }

    /**
     * Create an instance of {@link LabelSpecificationType }
     * 
     */
    public LabelSpecificationType createLabelSpecificationType() {
        return new LabelSpecificationType();
    }

    /**
     * Create an instance of {@link TranslateType }
     * 
     */
    public TranslateType createTranslateType() {
        return new TranslateType();
    }

    /**
     * Create an instance of {@link LabelDeliveryType }
     * 
     */
    public LabelDeliveryType createLabelDeliveryType() {
        return new LabelDeliveryType();
    }

    /**
     * Create an instance of {@link LRUPSPremiumCareFormType }
     * 
     */
    public LRUPSPremiumCareFormType createLRUPSPremiumCareFormType() {
        return new LRUPSPremiumCareFormType();
    }

    /**
     * Create an instance of {@link ReferenceNumberType }
     * 
     */
    public ReferenceNumberType createReferenceNumberType() {
        return new ReferenceNumberType();
    }

    /**
     * Create an instance of {@link LabelLinkIndicator }
     * 
     */
    public LabelLinkIndicator createLabelLinkIndicator() {
        return new LabelLinkIndicator();
    }

    /**
     * Create an instance of {@link LabelStockSizeType }
     * 
     */
    public LabelStockSizeType createLabelStockSizeType() {
        return new LabelStockSizeType();
    }

    /**
     * Create an instance of {@link CodeType }
     * 
     */
    public CodeType createCodeType() {
        return new CodeType();
    }

    /**
     * Create an instance of {@link ImageFormatCodeType }
     * 
     */
    public ImageFormatCodeType createImageFormatCodeType() {
        return new ImageFormatCodeType();
    }

}
