//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.26 at 09:37:53 AM KST 
//


package com.ups.timeintransit.timeintransitrequest;

import lombok.Builder;
import lombok.NoArgsConstructor;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransitToAddressArtifactFormatType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransitToAddressArtifactFormatType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}AddressArtifactFormatType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}ResidentialAddressIndicator" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@NoArgsConstructor
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransitToAddressArtifactFormatType", propOrder = {
    "residentialAddressIndicator"
})
public class TransitToAddressArtifactFormatType
    extends AddressArtifactFormatType
{

    @Builder(builderMethodName = "builderMethod")
    public TransitToAddressArtifactFormatType(String politicalDivision3, String politicalDivision2, String politicalDivision1, String country, String countryCode, String postcodePrimaryHigh, String postcodePrimaryLow, String residentialAddressIndicator) {
        super(politicalDivision3, politicalDivision2, politicalDivision1, country, countryCode, postcodePrimaryHigh, postcodePrimaryLow);
        this.residentialAddressIndicator = residentialAddressIndicator;
    }

    @XmlElement(name = "ResidentialAddressIndicator")
    protected String residentialAddressIndicator;

    /**
     * Gets the value of the residentialAddressIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResidentialAddressIndicator() {
        return residentialAddressIndicator;
    }

    /**
     * Sets the value of the residentialAddressIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResidentialAddressIndicator(String value) {
        this.residentialAddressIndicator = value;
    }

}
